// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nostrification.Infrastructure.Persistence;

#nullable disable

namespace Nostrification.Infrastructure.Migrations
{
    [DbContext(typeof(NostrificationDbContext))]
    [Migration("20251203140607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nostrification.Domain.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnswerFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppostilFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClaimerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentNode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiplomGetDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiplomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiplomSeria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FromOperator")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorOrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OwnCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OwnUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PINF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StudyEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudyStepId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("UniversityAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniversityCountry")
                        .HasColumnType("int");

                    b.Property<string>("UniversityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<string>("country_educated_gos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_number_diploma_gos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("graduation_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("head_organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_head_education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_institution_gos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("refer_registr_numb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registry_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rejection_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("series_doc_diploma_gos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimerTypeId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegionId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudyStepId");

                    b.HasIndex("StudyTypeId");

                    b.HasIndex("UniversityCountry");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.ClaimStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClaimStatuses");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.ClaimerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClaimerTypes");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameUz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameUz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("XtbName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.StudyStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudySteps");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.StudyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyTypes");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.Claim", b =>
                {
                    b.HasOne("Nostrification.Domain.Entities.ClaimerType", "ClaimerType")
                        .WithMany()
                        .HasForeignKey("ClaimerTypeId");

                    b.HasOne("Nostrification.Domain.Entities.Region", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("Nostrification.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Nostrification.Domain.Entities.ClaimStatus", "ClaimStatus")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("Nostrification.Domain.Entities.StudyStep", "StudyStep")
                        .WithMany()
                        .HasForeignKey("StudyStepId");

                    b.HasOne("Nostrification.Domain.Entities.StudyType", "StudyType")
                        .WithMany()
                        .HasForeignKey("StudyTypeId");

                    b.HasOne("Nostrification.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("UniversityCountry");

                    b.Navigation("ClaimStatus");

                    b.Navigation("ClaimerType");

                    b.Navigation("Country");

                    b.Navigation("District");

                    b.Navigation("Region");

                    b.Navigation("StudyStep");

                    b.Navigation("StudyType");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.Region", b =>
                {
                    b.HasOne("Nostrification.Domain.Entities.Region", "District")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Nostrification.Domain.Entities.User", b =>
                {
                    b.HasOne("Nostrification.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Nostrification.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Region");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
